- tasks/system/SLES-12/install_docker.yml
Due to locking issues with zypper, retry the "Reload repositories" step
> SLES12: Retry "Reload repositories" step

- README.md
- defaults/main.yml
- tasks/system/CentOS-7/install_docker.yml
- tasks/system/CentOS-7/main.yml
- tasks/system/RedHat-7/install_dependencies.yml
- tasks/system/RedHat-7/install_docker.yml
- tasks/system/RedHat-7/main.yml
- tasks/system/general/make_user.yml
- vars/os_CentOS_7.yml
- vars/os_RedHat_7.yml
Everything should be back to where it was while the repo was private. This is a continuation of PR8. 
This request "Maybe we can add a field to the docker_version_map for RHEL add_docker_repo or so that is used here as a when: add_docker_repo is defined. This way we would only need to maintain that logic in the version map instead of going back to this task for new versions that get added later...
What do you think?" will be worked on now.
> Adding RHEL and CentOS support

- README.md
- defaults/main.yml
- tasks/system/general/setup_xfs.yml
- tasks/system/main.yml
Closes #14
When the lxc volume already exists we tried to recreate it. Since all sizes are relative, this is not idempotent. Therefore we skip the `setup_xfc` tasks when the lvm already exists. This behaiviour can be overwritten by setting `force_xfc: true`.
> Skip setup_xfc is lgv already exists

- README.md
- tasks/system/general/make_user.yml
Closes #15
In case the elastic user should not inherit the `.ssh/authorized_keys` file from the "ansible default user", it is now possible to specify a local path to an `authorized_keys` file to be copied.
> Add variable to define a local authorized_key file

- tasks/system/CentOS-7/main.yml
- tasks/system/RedHat-7/main.yml
According to the official installation guide the firewalld has to be disabled (permanently) on RHEL and CentOS installations.
> Disable firewalld on RHEL and CentOS

- defaults/main.yml
- tasks/system/general/set_limits.yml
Setting resource limits in '/etc/security/limits.conf' is probably not ideal.
First of all they only apply to users logged in via PAM, but are ignored by system services - my reading is that since ECE is started via systemd and not interactively these will be ignored.
Secondly the configuration files in 'etc/security/limits.d' (generally) override any settings in this file, which might lead to all sorts of weird behaviour.
I've therefore changed the task to write the limits to a distinct configuration file and additionally parameterized the file name to use.
> Do not use limits.conf to adjust system limits

- tasks/system/general/set_limits.yml
- tasks/system/general/sysctl_scripts.yml
#20 and #21 introduced custom destinations for sysctl related settings, but there was an indentation issue, this PR fixes those.
> Fix wrong indentation on sysctl destinations

- tasks/system/general/configure_docker.yml
We ran into some sort of race condition on RHEL 7.6 where docker.service wasn't available after the reboot.
One of our Linux Admins suggested that restarting the daemon prior to rebooting the system is unnecessary - making sure the service is enabled ('enabled: true') and forcing systemd to load all the changes ('daemon_reload: yes') is sufficient.
Since the only distro available to me is RedHat i don't know if SuSE, CentOS or Ubuntu might also be affected by this.
> Do not restart the docker service prior to reboot

- tasks/system/general/sysctl_scripts.yml
The 'ip_conntrack' module has to be loaded before changes are made to the network settings.
By using 'sysctl: set' every token will be validated and e.g. the setting
> name: 'net.netfilter.nf_conntrack_tcp_timeout_established', value: '7200'
will fail the task with
> sysctl: cannot stat /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_established: No such file or directory
in case the module is not loaded.
There is an additional catch: modprobe will load the module , but it's not persistent over reboots.
Forcing the module to be loaded by putting a '.conf' file into '/etc/modules-load.d/' might be a good idea.
> Module ip_conntrack has to be loaded before changes are applied

- README.md
- defaults/main.yml
- tasks/bootstrap/main.yml
- tasks/bootstrap/primary/install_stack.yml
- tasks/bootstrap/secondary/install_stack.yml
Closes #22 
This PR introduces a new variable `memory`which defines the [JVM heap sizes](https://www.elastic.co/guide/en/cloud-enterprise/current/ece-heap.html) of different services running in ECE.
`memory`is a simple dict that is then put into a json string to pass to the installer
```yaml
memory:
runner: 1G
allocator: 4G
proxy: 8G
zookeeper: 4G
director: 1G
constructor: 4G
adminconsole: 4G
- name: Create memory settings
set_fact:
memory_settings: ' {"runner":{"xms":"{{memory.runner}}","xmx":"{{memory.runner}}"},"proxy":{"xms":"{{memory.proxy}}","xmx":"{{memory.proxy}}"},"zookeeper":{"xms":"{{memory.zookeeper}}","xmx":"{{memory.zookeeper}}"},"director":{"xms":"{{memory.director}}","xmx":"{{memory.director}}"},"constructor":{"xms":"{{memory.constructor}}","xmx":"{{memory.constructor}}"}," …
```
> Adjustable memory settings

- tasks/system/RedHat-7/install_docker.yml
- templates/docker1.13.conf
Elastic recommends using the RPMs provided by RedHat - currently Docker 1.13
The way the role is set up a separate configuration file for Docker is required - called 'docker1.13.conf' - although the contents are currently identical to 'docker18.09.conf'.
I've also added an additional 'when' clause to the 'install_docker.yml' script to only add the Docker repository key if version '18.09' is to be installed.
As a side note:
I think it's likely that a RedHat Satellite server will be used to provide packages (that is the case at our company) for installation. In that case adding the 'extras' repository is not necessary (and will probably fail). Making that task optional by adding a 'skip' variable might help (e.g. in the 'docker1.13.conf' file?).
> Handling of Docker 1.13 on RHEL systems

- tasks/system/general/kernel_modules.yml
- tasks/system/main.yml
Closes #29
Adds a new `kernel_,modules.yml` file to make sure kernel modules are loaded on every reboot.
> Make sure to load overlay and ip_conntrack modules

- README.md
- defaults/main.yml
- tasks/diagnostics/main.yml
- tasks/main.yml
PR for issue https://github.com/elastic/ansible-elastic-cloud-enterprise/issues/38
The ansible role runs successfully until executing the diagnostics.sh - following steps could not be tested correctly because I currently don´t have an ECE running.
Following improvements could be done:
- Alter download url - currently hard coded to github download of v1.1
- v1.1 also hardcoded in task `Run ece support diagnostics`
- arguments passed to diagnostics.sh are also hardcoded
> Add support for ece support diagnostics

- README.md
- defaults/main.yml
- tasks/main.yml
Using a variable instead of a tag allows a default run without diagnostics which is what most users would want in most cases
> Create a var to define if diagnostics should be fetched

- vars/os_Ubuntu_16.yml
related to  https://github.com/elastic/cloud/issues/46198
https://github.com/elastic/cloud/pull/47911 was not enough to make ubuntu working: docker was not installing with the version set in params. Actually `docker-ce` package is installing with the right version requested (18.09 ) but not `docker-ce-cli` (19.x aka latest).
> Fix docker install for ubuntu

- tasks/system/RedHat-7/install_docker.yml
- tasks/system/general/configure_docker.yml
- vars/os_RedHat_7.yml
Related to https://github.com/elastic/cloud/issues/50009
**Yum REPO:** 
Docker 1.13 was not installing because (wrong repo for RHEL 7.7, different for <= 7.6)
**Docker service config:**
Docker conf in `/usr/lib/systemd/system/docker.service` does contain a specific conf for `docker-proxy` and `docker-runc`:
```
ExecStart=/usr/bin/dockerd-current \
--add-runtime docker-runc=/usr/libexec/docker/docker-runc-current \
--default-runtime=docker-runc \
--authorization-plugin=rhel-push-plugin \
--exec-opt native.cgroupdriver=systemd \
--userland-proxy-path=/usr/libexec/docker/docker-proxy-current \
--init-path=/usr/libexec/docker/docker-init-current \
--seccomp-profile=/etc/docker/seccomp.json \
$OPTIONS \
$DOCKER_STORAGE_OPTIONS \
$DOCKER_NETWORK_OPTIONS \
$ADD_REGISTRY \
$BLOCK_REGISTRY \ …
```
> Fix RHEL-7

- tasks/system/CentOS-7/install_Docker-CE.yml
- tasks/system/CentOS-7/install_Docker-CS.yml
- tasks/system/CentOS-7/install_docker.yml
- vars/os_CentOS_7.yml
Related to https://github.com/elastic/cloud/issues/50010
This will fix the following issues:
- `docker-ce-cli` is missing, and so it will install `docker-ce-cli` 19 (latest) and not 18 as requested
- add possibilty to install docker 1.13, without SELinux (for now): [ECE is supported by docker 1.13 on centos 7](https://www.elastic.co/guide/en/cloud-enterprise/current/ece-prereqs-software.html)
> Fix playbook for CentOS 7

- tasks/system/CentOS-7/install_Docker-CE.yml
- tasks/system/CentOS-7/install_Docker-CS.yml
- vars/os_CentOS_7.yml
Since few days, we get this error: 
```
failed to fetch key at https://sks-keyservers.net/pks/lookup?op=get&search=0xee6d536cf7dc86e2d7d56f59a178ac6c6238f52e , error was: HTTP Error 502: Bad Gateway
```
> Fix docker gpg repo key for Centos

- README.md
- defaults/main.yml
- tasks/ece-bootstrap/primary/install_stack.yml
- tasks/ece-bootstrap/secondary/install_stack.yml
Somehow managed to get in a pickle with branching and delete the original PR. Apologies @vaubarth ...
Hopefully addresses your concerns from https://github.com/elastic/ansible-elastic-cloud-enterprise/pull/65
> added ece_runner_id to allow runner_id to be set at install time

- README.md
- defaults/main.yml
- tasks/base/CentOS-7/install_dependencies.yml
- tasks/base/CentOS-7/main.yml
- tasks/base/general/configure_docker.yml
- templates/docker1.13.conf
- templates/docker18.09.conf
This PR allows to configure the docker bridge-ip using ansible vars. 
In some environments the default bridge-ip overlaps with the host subnet and may cause some issues with iptables. By setting the variable the IP can be changed.
Also updated README.md
> Make docker bridge ip configurable, Install dependencies like in RedHat-7

- tasks/direct-install/main.yml
Resolved conflict of previous PR (had commits from other PR still in the working branch). 
Replaced the 'reboot' shell command with the 'reboot' Ansible module, which is the recommended way to reboot servers in Ansible Playbooks
> Replace shell reboot command with Ansible reboot module

- tasks/direct-install/setup_xfs.yml
The way volume mounts are done currently causes an error when running the playbook a second time, because the volume is already mounted. Also, lines to `/etc/fstab` are added manually. This PR replaces the current approach with the Ansible `mount` module to make volume mounts idempotent. 
The mount module will create the entries in `/etc/fstab` as well as ensure the volume is mounted. If it is already mounted, Ansible will continue to execute the play.
> Make volume mounts idempotent by using ansible 'mount' module

- tasks/base/RedHat-8/install_dependencies.yml
- tasks/base/RedHat-8/install_docker.yml
- tasks/base/RedHat-8/main.yml
- vars/os_RedHat_8.yml
RHEL8 has some caveats
* Works when `ansible_python_interpreter: /usr/libexec/platform-python`. No default python is installed in RHEL8 but the above link refers to python3
* docker packages are not made available and have to be fetched from CentOS repos
* containerd.io has to be installed before docker can be installed (managed by the playbook)
> Add support for RHEL 8

- tasks/base/CentOS-7/install_dependencies.yml
- templates/format-drives.j2
Looks like `mdadm` is missing on centos. Not sure why, but it's missing...
> add mdadm to centos

- README.md
- tasks/base/CentOS-8/install_dependencies.yml
- tasks/base/CentOS-8/install_docker.yml
- tasks/base/CentOS-8/main.yml
- vars/os_CentOS_8.yml
- vars/os_RedHat_7.yml
- vars/os_RedHat_8.yml
- vars/os_Ubuntu_16.yml
Related to https://github.com/elastic/cloud/issues/63409
This is adding CentOS 8
> Add CentOS 8 (with Docker 19)

- tasks/direct-install/main.yml
During migration to the new structure for vm images the tags for xfs and mount operations got lost.
This PR re-adds `setup_filesystem` to both tasks and also add `destructive` to `setup_xfs.yml`.
Closes #82
> Re-add setup_filesystem tag for xfs and mount operations

- tasks/base/general/setup_mount_permissions.yml
A quote was missing in `tasks/base/general/setup_mount_permissions.yml`
> Fixing malformated file

- defaults/main.yml
Related to https://github.com/elastic/ansible-elastic-cloud-enterprise/issues/80 and bumping the default version to the very last version
﻿
> Bump ECE default version to 2.6.1

- tasks/base/general/dependencies.yml
- tasks/base/main.yml
Fixing https://github.com/elastic/ansible-elastic-cloud-enterprise/issues/62
Cloud-init is required by this ansible playbooks and failed if not pre-installed. Let's install it  if it was not already the case
> Install cloud-init by default

- tasks/base/general/configure_docker.yml
Related to https://github.com/elastic/ansible-elastic-cloud-enterprise/issues/100
When trying to install with `docker_version: 19.03` the docker config file is not copied over, resulting with not using the secondary disk as docker storage
> Fix task copying docker config

- tasks/base/CentOS-8/install_dependencies.yml
- templates/format-drives.j2
As explained in https://github.com/elastic/sdh-cloud/issues/11718 `mdadm` is ignored when rebooting.
In order to reproduce the issue you need at least two secondary disks, with Centos 
I'll test this PR by creating new AMIs with this PR
Please note that this does not have any impact on ansible-playbook direct install mode since we are not currently supporting more than one secondary disk (configured with `device_name`)
> Fix MDADM on reboot

- CONTRIBUTING.md
- tasks/base/SLES-12/install_docker.yml
- vars/os_SLES_12.yml
Closes https://github.com/elastic/cloud/issues/73576
This is bumping SLES_12 to **SP5** and **docker 19**
> Bump SLES to SP5 with docker 19

- tasks/direct-install/setup_xfs.yml
This PR solves issues with LVM when re-running the playbook after a failed run, when external disk is already formatted and swap partition is already created:
```
TASK [ansible-elastic-cloud-enterprise : Create data volume] ***************************************************************
fatal: [host1]: FAILED! => {"changed": false, "msg": "Sorry, no shrinking of data to 0 permitted."}
```
```
TASK [ansible-elastic-cloud-enterprise : Setup swap] ***********************************************************************
fatal: [host1]: FAILED! => {"changed": true, "cmd": ["mkswap", "/dev/lxc/swap"], "delta": "0:00:00.004355", "end": "2021-03-15 17:57:19.994434", "msg": "non-zero return code", "rc": 1, "start": "2021-03-15 17:57:19.990079", "stderr": "mkswap: error: /dev/lxc/swap is mounted; …
```
> Preventing errors with LVM when re-running the playbook

- defaults/main.yml
Updates the support diagnostics URL to a more recent version. The one used here is released in Dec 12, 2018
> Update the outdated ece_supportdiagnostics_url

- README.md
The small and medium playbook link were causing a 404's as the pages were moved and do now live in a different place on /current/.
> Fixed link for "small playbook"

- tasks/base/CentOS-8/install_dependencies.yml
- tasks/base/CentOS-8/install_docker.yml
- vars/os_CentOS_7.yml
- vars/os_CentOS_8.yml
- vars/os_Ubuntu_16.yml
- vars/os_Ubuntu_18.yml
Closing https://github.com/elastic/ansible-elastic-cloud-enterprise/issues/121 
Also for some reason, like for [rhel-8](https://github.com/elastic/ansible-elastic-cloud-enterprise/pull/98) , I needed to add iptable for centos-8
> Pin containerd for centos and ubuntu

- defaults/main.yml
This updates the default ECE version to 2.11.0 and bumps the support diagnostics version to 1.3. While v2.0.1 is available, there are breaking changes which have not been tested in the context of this playbook.
> Update default ECE version to 2.11.0

- defaults/main.yml
ECE 2.12.0 has been released, we can bump the default version here
> Bumpt ECE version to 2.12.0

- README.md
- tasks/ece-bootstrap/secondary/install_stack.yml
Until now, one had to manually override the Ansible task to use `--capacity`. This PR exposes a new `capacity` parameter that does just that. If left empty, the old behavior is used.
> Allow allocator capacity configuration

- defaults/main.yml
ECE 3.1.1 has been released so we're bumping the version.
> Bump default version of ECE to 3.1.1

- vars/os_CentOS_7.yml
- vars/os_CentOS_8.yml
- vars/os_RedHat_7.yml
- vars/os_RedHat_8.yml
Hi team, 
Found out that grub2-mkconfig is not a direct equivalent to update-grub on Debian-based systems :) 
This is what update-grub actually does: 
```
cat /usr/sbin/update-grub
#!/bin/sh
set -e
exec grub-mkconfig -o /boot/grub/grub.cfg "$@"
```
So just executing grub2-mkconfig on RHEL-based distributions outputs the contents to stdout and that's it...
I'm using the symlink in `/etc` I verified its existence in CentOs 7 and RHEL 8 so I believe CentOS 8 and RHEL7 should work the same. It's also in the product [documentation](https://www.elastic.co/guide/en/cloud-enterprise/current/ece-configure-hosts-rhel-centos-cloud.html#ece-supported-kernel-rhel-cloud)
In the current state, this playbook does not configure any RHEL system properly so I believe this fix is rather urgent. 
Thank you.
> RHEL-based distributions grub.cfg are not updated

- templates/docker.conf
According to [ECE installer](https://www.elastic.co/guide/en/cloud-enterprise/current/ece-installation-script.html) and our test suite, we should default to `/var/run/docker.sock` instead of `/run/docker.sock`.
NB: on some OS, we force docker.service to listen on `/run/docker.sock` while `docker.socket` service listen on `/var/run/docker.sock`
> Docker listen to /var/run/docker.sock

- defaults/main.yml
ECE 3.2.1 was just released, update the default version to be just that.
> Bump default ECE to 3.2.1

- README.md
- tasks/ece-bootstrap/main.yml
Instead of downloading the ECE installer script, this will copy it from controller machine to remote host. 
This `ece_installer_path` is optional. If missing, it will try to download it from the internet, unless the file already exists at destination (`/home/elastic/elastic-cloud-enterprise.sh`)
> Variable to copy installer script instead of downloading it

- tasks/base/general/configure_docker.yml
- tasks/ece-bootstrap/main.yml
We need to start docker back up prior to checking `docker ps` here: https://github.com/elastic/ansible-elastic-cloud-enterprise/blob/09bf023251380a30f114df3c478c288e0c4c6905/tasks/ece-bootstrap/main.yml#L30
This issue references the bug this PR should help resolve:
https://github.com/elastic/ansible-elastic-cloud-enterprise/issues/109
> Ansible doesn't verify docker as running

- .gitignore
- vars/os_Ubuntu_20.yml
Remove specific architecture from the repo specification to make it work on ARM too.
> Ubuntu 20.04 ARM support

- defaults/main.yml
- tasks/ece-bootstrap/primary/install_stack.yml
- tasks/ece-bootstrap/secondary/install_stack.yml
This PR adds a new  `extra_installer_args` var to allow passing arbitrary additional arguments to the installer on fresh install.
> Add a new variable to allow passing additional installer arguments

- tasks/direct-install/setup_xfs.yml
For current versions of Ansible:
"The warn parameter to these modules is now deprecated and defaults to False."
Source: https://github.com/ansible/ansible/blob/v2.11.0/changelogs/CHANGELOG-v2.11.rst#deprecated-features
While I understand this role is only tested to Ansible v2.8.7, removing these two lines was all I needed to get the role to work on CentOS 8 AMIs with a current version of Ansible (core 2.15.1). 
I believe for older versions of Ansible, the missing "warn" parameter will only warn, not fail for the swapoff command here.
> Update setup_xfs.yml, remove deprecated "args: warn"

- defaults/main.yml
Relates to https://github.com/elastic/release-eng/issues/722
> Bump default to latest ECE release - 3.6.0

- defaults/main.yml
ECE 3.7.2 (based on ms-105) was release on 27th June .
This PR updates version used by ansible repo to latest
> update version in ansible
